package Enums;

public enum Servicos {
    REVIASAO_COMPLETA,
    TROCA_DE_OLEO,
    TROCA_DE_PASTILHA_DE_FREIO,
    TROCA_DE_DISCO_DE_FREIO,
    TROCA_DE_EMBREAGEM,
    HIGIENIZACAO_AR_CONDICIONADO,
    SAGRIA_DO_OLEO_DE_FREIO,
    LIMPEZA_DO_TBI,
    TROCA_DE_AMORTECIMENTO,
    TROCA_DE_VELA,
    TROCA_DE_TENSOR,
    TROCA_DE_CORREIA_DENTADA,
    ATENDIMENTO_RÁPIDO

}
